version: "3.9"

services:
  api:
    container_name: api-fastify
    build:
      context: .
      dockerfile: Dockerfile
      target: devrunner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    tty: true
    command: pnpm dev
    volumes:
      - ./:/app